services:
  apim:
    image: wso2-apim:4.6.0-jdk21
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APIM_URL=${APIM_URL}
        - APIM_FOLDER=${APIM_FOLDER}
        - IS_URL=${IS_URL}
        - IS_FOLDER=${IS_FOLDER}
        - APICTL_URL_ARM64=${APICTL_URL_ARM64}
        - APICTL_URL_X64=${APICTL_URL_X64}
        - IS_PORT_OFFSET=${IS_PORT_OFFSET:-3}
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8243:8243"
      - "8280:8280"
      - "9446:9446" # Puerto fijo mapeado para el WSO2 IS (9443 + Offset)
    command: ["${WSO2_MODE:-apim}"] 
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9443"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./src/openapi:/opt/src/openapi